FROM node:18-alpine

WORKDIR /app

RUN npm install -g @angular/cli

# Cria diretório do projeto Angular
WORKDIR /app/rommanel-ui

# Só define comando inicial vazio, você rodará manualmente o ng new
CMD [ "sh" ]
