services:
  api:
    build:
      context: ./backend
      dockerfile: src/Rommanel.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__Default=Host=db;Database=rommanel;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rommanel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test:
    build:
      context: ./backend
      dockerfile: tests/Rommanel.UnitTests/Dockerfile
    volumes:
      - ./coverage:/app/coverage
    depends_on:
      - db

  report:
    build:
      context: ./tools/reportgenerator
    volumes:
      - ./coverage:/coverage
    depends_on:
      - test

  coverage-server:
    image: nginx:alpine
    depends_on:
      - report
    ports:
      - "5005:80"
    volumes:
      - ./coverage/report:/usr/share/nginx/html:ro

volumes:
  pgdata:
